### ISSUE TITLE
When shouldCallAPI() returns false it should resolve instead of  returning undefined (discussion)

### ISSUE THREAD

**Issue by georapbox** [georapbox/redux-call-api-middleware#1]
```js
// actions.js

export function loadPosts(userId) {
  return {
    types: {
      requestType: 'LOAD_POSTS_REQUEST',
      successType: 'LOAD_POSTS_SUCCESS',
      failureType: 'LOAD_POSTS_FAILURE'
    },
    shouldCallAPI: state => false,
    callAPI: (dispatch, state) => fetch(`http://myapi.com/users/${userId}/posts`),
    payload: { userId }
  }
}

// MyComponent.js

import React from 'react';
import { connect } from 'react-redux';
import { loadPosts } from './actions.js';

const MyComponent = props => {
  props.loadUserPosts('12345').then(res => {
    console.log(res);
  });
};

const mapDispatchToProps = dispatch => ({
  loadUserPosts: userId => dispatch(loadPosts(userId))
});

export default connect(null, mapDispatchToProps)(MyComponent);
```

In the example above, `shouldCallAPI()` returns false. Now when I call `loadUserPosts` and chain with  a`.then` handler it will throw a TypeError because the middleware returns `undefined`. The conclusion is that when `shouldCallAPI()` is used and I need to chain I must always check if the returned result is undefined.

```js
 const userPosts = props.loadUserPosts('12345');

if (userPosts) {
  userPosts.then(res => {
    console.log(res);
  });
}
```

Possible solutions:

- The middleware could return `Promise.resolve()` when `shouldCallAPI()` is false instead of `undefined`. This way chaining would not lead to error.

**Comment by dtsolis** [comment]
Returning a promise sounds good as you, as a consumer of the api, can always expect a promise to be returned. Maybe, also resolve the current state (?).

**Comment by georapbox** [comment]
@dtsolis I'm not sure of resolving to current state. The user expects the response or error from the API to be resolved. Instead in this case if the state is resolved could that lead to confusion? Furthermore, inside the `then` handler, the user always has access to the whole state through the connected component. Maybe resolve to something more meaningful, like a message indicating that the API was not called?

**Comment by dtsolis** [comment]
You’re right, it could lead to confusion. Yes, a message makes more sense.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
